# Generated by Django 2.2.6 on 2020-02-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=40, null=True, verbose_name='审核备注')),
                ('state', models.CharField(blank=True, choices=[('1', '未审核'), ('2', '审核通过'), ('3', '审核拒绝')], default='1', max_length=50, null=True, verbose_name='审核状态')),
                ('applier', models.CharField(blank=True, max_length=10, null=True, verbose_name='申请人')),
                ('auditor', models.CharField(blank=True, max_length=10, null=True, verbose_name='审核人')),
                ('applyTime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('audiTime', models.DateTimeField(auto_now=True, verbose_name='审核时间')),
                ('realName', models.CharField(blank=True, max_length=10, null=True, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6)),
                ('idNumber', models.CharField(blank=True, max_length=25, null=True, verbose_name='身份证号码')),
                ('bornDate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='家庭地址')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='身份证正面地址')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='身份证反面地址')),
                ('file', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': '待实名认证',
                'verbose_name_plural': '待实名认证',
            },
        ),
        migrations.CreateModel(
            name='RealAuthAuditted',
            fields=[
            ],
            options={
                'verbose_name': '已实名认证',
                'verbose_name_plural': '已实名认证',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('certification.realauth',),
        ),
    ]
