# Generated by Django 2.2.6 on 2020-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='remark',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='审核备注'),
        ),
    ]
