# Generated by Django 2.2.6 on 2020-02-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20200216_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='audiTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
    ]
