# Generated by Django 2.2.6 on 2020-02-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_auto_20200216_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='state',
            field=models.CharField(blank=True, choices=[('STATE_NORMAL', '未审核'), ('STATE_AUDIT', '审核通过'), ('STATE_REJECT', '审核拒绝')], default='STATE_NORMAL', max_length=50, null=True, verbose_name='审核状态'),
        ),
    ]
