# Generated by Django 2.2.6 on 2020-02-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20200217_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, '未审核'), (2, '审核通过'), (3, '审核拒绝')], default=1, null=True, verbose_name='审核状态'),
        ),
    ]
