# Generated by Django 2.2.6 on 2020-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_auto_20200217_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '审核通过'), (2, '审核拒绝')], default=0, null=True, verbose_name='审核状态'),
        ),
    ]
