# Generated by Django 2.2.6 on 2020-02-19 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification', '0008_auto_20200218_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realauth',
            name='applier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.CreateModel(
            name='VedioAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, max_length=40, null=True, verbose_name='审核备注')),
                ('state', models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '审核通过'), (2, '审核拒绝')], default=0, null=True, verbose_name='审核状态')),
                ('auditor', models.CharField(blank=True, max_length=10, null=True, verbose_name='审核人')),
                ('applyTime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('audiTime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('applier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '视频认证',
                'verbose_name_plural': '视频认证',
            },
        ),
    ]
