# Generated by Django 2.2.6 on 2020-02-19 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certification', '0009_auto_20200219_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, max_length=40, null=True, verbose_name='审核备注')),
                ('state', models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '审核通过'), (2, '审核拒绝')], default=0, null=True, verbose_name='审核状态')),
                ('auditor', models.CharField(blank=True, max_length=10, null=True, verbose_name='审核人')),
                ('applyTime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('audiTime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m', verbose_name='分控材料图片')),
                ('fileType', models.CharField(blank=True, max_length=20, null=True, verbose_name='分控材料分类')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分控材料评分')),
                ('applier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
