# Generated by Django 2.2.6 on 2020-02-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0010_userfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'verbose_name': '分控材料认证', 'verbose_name_plural': '分控材料认证'},
        ),
    ]
