# Generated by Django 2.2.6 on 2020-02-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0011_auto_20200219_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfile',
            options={'verbose_name': '风控材料认证', 'verbose_name_plural': '风控材料认证'},
        ),
    ]
