# Generated by Django 2.2.6 on 2020-02-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0012_auto_20200220_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileAudit',
            fields=[
            ],
            options={
                'verbose_name': '风控材料已认证',
                'verbose_name_plural': '风控材料已认证',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('certification.userfile',),
        ),
    ]
