# Generated by Django 2.2.6 on 2020-02-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0013_userfileaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='fileType',
            field=models.CharField(blank=True, choices=[(1, '工作证明'), (2, '房产证正面'), (3, '房产证反面'), (4, '户口本'), (5, '结婚证'), (6, '银行流水证明'), (7, '学位证'), (8, '毕业证')], max_length=20, null=True, verbose_name='分控材料分类'),
        ),
    ]
