# Generated by Django 2.2.6 on 2020-02-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0015_auto_20200220_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='fileType',
            field=models.IntegerField(blank=True, choices=[(0, '无'), (1, '工作证明'), (2, '房产证正面'), (3, '房产证反面'), (4, '户口本'), (5, '结婚证'), (6, '银行流水证明'), (7, '学位证'), (8, '毕业证')], default=0, null=True, verbose_name='分控材料分类'),
        ),
    ]
