# Generated by Django 2.2.6 on 2020-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0017_userbankninfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBanknInfo',
        ),
    ]
