# Generated by Django 2.2.6 on 2020-02-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0022_auto_20200222_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnType', models.IntegerField(blank=True, null=True, verbose_name='还款类型(等额本息)')),
                ('bidRequestType', models.IntegerField(blank=True, null=True, verbose_name='借款类型(信用标)')),
                ('bidRequestState', models.IntegerField(blank=True, null=True, verbose_name='借款状态')),
                ('bidRequestAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='借款总金额')),
                ('currentRate', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='年化利率')),
                ('minBidAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='最小借款金额')),
                ('monthes2Return', models.IntegerField(blank=True, null=True, verbose_name='还款月数')),
                ('bidCount', models.IntegerField(blank=True, default=0, null=True, verbose_name='已投标次数(冗余)')),
                ('totalRewardAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='总回报金额(总利息)')),
                ('currentSum', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='当前已投标总金额')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='借款标题')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='借款描述')),
                ('note', models.TextField(blank=True, max_length=100, null=True, verbose_name='风控意见')),
                ('disableDate', models.DateTimeField(blank=True, null=True, verbose_name='招标截止日期')),
                ('disableDays', models.IntegerField(blank=True, null=True, verbose_name='招标天数')),
                ('applyTime', models.DateTimeField(blank=True, null=True, verbose_name='这个标的申请时间')),
                ('publishTime', models.DateTimeField(blank=True, null=True, verbose_name='发标时间')),
                ('createUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Borrower', verbose_name='借款人')),
            ],
            options={
                'verbose_name': '借款对象表',
                'verbose_name_plural': '借款对象表',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualRate', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='年化利率')),
                ('availableAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='这次投标金额')),
                ('bidRequestTitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='借款标题')),
                ('bidTime', models.DateTimeField(blank=True, null=True, verbose_name='投标时间')),
                ('bidRequestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BidRequest', verbose_name='借款标来源')),
                ('bidUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Investor', verbose_name='投标人')),
            ],
            options={
                'verbose_name': '一次投资对象表',
                'verbose_name_plural': '一次投资对象表',
            },
        ),
    ]
