# Generated by Django 2.2.6 on 2020-02-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200228_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAuditOne',
            fields=[
            ],
            options={
                'verbose_name': '满标一审',
                'verbose_name_plural': '满标一审',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('business.bidrequestaudithistory',),
        ),
        migrations.CreateModel(
            name='FullAuditTwo',
            fields=[
            ],
            options={
                'verbose_name': '满标二审',
                'verbose_name_plural': '满标二审',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('business.bidrequestaudithistory',),
        ),
        migrations.AlterModelOptions(
            name='bidrequestaudithistory',
            options={'verbose_name': '发标前审核', 'verbose_name_plural': '发标前审核'},
        ),
        migrations.AlterField(
            model_name='bidrequestaudithistory',
            name='auditType',
            field=models.IntegerField(blank=True, choices=[(0, '发标前审核'), (1, '满标一审'), (2, '满标二审')], default=0, null=True, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='bidrequestaudithistory',
            name='bidRequestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.BidRequest', verbose_name='标对象'),
        ),
    ]
