# Generated by Django 2.2.6 on 2020-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_platformbankinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbankinfo',
            name='bankName',
            field=models.IntegerField(blank=True, null=True, verbose_name='银行名称'),
        ),
    ]
