# Generated by Django 2.2.6 on 2020-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20200301_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformbankinfo',
            name='bankName',
            field=models.IntegerField(blank=True, choices=[(1, '中国工商银行'), (2, '中国农业银行'), (3, '中国建设银行'), (4, '中国招商银行'), (5, '中国民生银行'), (6, '中国交通银行'), (7, '中国银行'), (8, '中信银行'), (9, '广发银行'), (10, '兴业银行'), (11, '华夏银行'), (12, '上海银行'), (13, '北京银行'), (14, '光大银行'), (15, '平安银行'), (16, '中国信合'), (17, '广州银行'), (18, '南京银行'), (19, '深圳发展银行'), (20, '中国邮政储蓄银行'), (21, '浦发银行'), (22, '广州农村商业银行')], null=True, verbose_name='银行名称'),
        ),
    ]
