# Generated by Django 2.2.6 on 2020-03-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_rechargeoffline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rechargeoffline',
            options={'verbose_name': '充值审核', 'verbose_name_plural': '充值审核'},
        ),
    ]
