# Generated by Django 2.2.6 on 2020-03-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userprofile_score'),
        ('business', '0009_auto_20200301_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='变化的余额')),
                ('tradeTime', models.DateTimeField(blank=True, null=True, verbose_name='变化的时间')),
                ('accountType', models.IntegerField(blank=True, null=True, verbose_name='资金变化类型')),
                ('usableAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='变化之后的可用余额')),
                ('freezedAmount', models.DecimalField(decimal_places=4, default=0.0, max_digits=18, verbose_name='变化之后的冻结金额')),
                ('note', models.TextField(blank=True, max_length=100, null=True, verbose_name='账户流水说明')),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account', verbose_name='用户账户')),
            ],
            options={
                'verbose_name': '账户流水',
                'verbose_name_plural': '账户流水',
            },
        ),
    ]
