# Generated by Django 2.2.6 on 2020-03-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_accountflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountflow',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account', verbose_name='用户账户'),
        ),
        migrations.AlterField(
            model_name='accountflow',
            name='accountType',
            field=models.IntegerField(blank=True, choices=[(0, '线下充值'), (1, '提现成功'), (2, '成功借款'), (3, '成功投标'), (4, '还款'), (5, '回款'), (6, '支付平台管理费'), (7, '利息管理费'), (8, '提现手续费'), (9, '充值手续费'), (10, '投标冻结金额'), (11, '取消投标冻结金额'), (12, '提现申请冻结金额'), (13, '提现申请失败取消冻结金额')], null=True, verbose_name='资金变化类型'),
        ),
    ]
