# Generated by Django 2.2.6 on 2020-03-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20200302_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountflow',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account', verbose_name='用户账户'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidRequestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='business.BidRequest', verbose_name='借款标来源'),
        ),
    ]
