# Generated by Django 2.2.6 on 2020-03-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20200308_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountflow',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account', verbose_name='用户账户'),
        ),
        migrations.AlterField(
            model_name='paymentscheduledetail',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentScheduleDetails', to='users.Borrower', verbose_name='还款人'),
        ),
        migrations.AlterField(
            model_name='paymentscheduledetail',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentScheduleDetails', to='users.Investor', verbose_name='收款人'),
        ),
    ]
