# Generated by Django 2.2.6 on 2020-03-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20200310_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneywithdraw',
            old_name='amount',
            new_name='moneyAmount',
        ),
        migrations.AlterField(
            model_name='accountflow',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account', verbose_name='用户账户'),
        ),
    ]
