# Generated by Django 2.2.6 on 2020-03-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
    ]
