# Generated by Django 2.2.6 on 2020-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0002_auto_20200322_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publishTime',
            field=models.DateTimeField(verbose_name='发表时间时间'),
        ),
    ]
