# Generated by Django 2.2.6 on 2020-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnews', '0003_auto_20200322_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='url',
        ),
    ]
