# Generated by Django 2.2.6 on 2019-10-26 13:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_investor', models.BooleanField(default=False)),
                ('is_borrower', models.BooleanField(default=False)),
                ('realName', models.CharField(default='', max_length=50, verbose_name='真实昵称')),
                ('birdDate', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6)),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码')),
                ('kyc_complete', models.CharField(blank=True, max_length=1, null=True, verbose_name='验证程度')),
                ('escrow_account_number', models.CharField(blank=True, max_length=1, null=True, verbose_name='银行存管账号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('current_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='当前地址')),
                ('permanent_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='永久地址')),
                ('highest_qualification', models.CharField(blank=True, choices=[('NONE', '无'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], default='无', max_length=50, null=True)),
                ('passout_year', models.DateField(blank=True, null=True, verbose_name='毕业日期')),
                ('university_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='大学名称')),
            ],
            options={
                'verbose_name': '贷款者信息表',
                'verbose_name_plural': '贷款者信息表',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('investment_limit', models.IntegerField(default=5000, verbose_name='投资限额')),
                ('fund_committed', models.IntegerField(verbose_name='承诺金额')),
            ],
            options={
                'verbose_name': '投资者信息表',
                'verbose_name_plural': '投资者信息表',
            },
        ),
    ]
