# Generated by Django 2.2.6 on 2019-12-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birdDate',
            new_name='bornDate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='realName',
            new_name='trueName',
        ),
    ]
