# Generated by Django 2.2.6 on 2019-12-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191216_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'verbose_name': '借贷信息表', 'verbose_name_plural': '借贷信息表'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': '投资信息表', 'verbose_name_plural': '投资信息表'},
        ),
        migrations.AlterField(
            model_name='investor',
            name='fund_committed',
            field=models.IntegerField(default=0, verbose_name='承诺金额'),
        ),
    ]
