# Generated by Django 2.2.6 on 2019-12-26 19:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191218_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerUserProfile',
            fields=[
            ],
            options={
                'verbose_name': '贷款者',
                'verbose_name_plural': '贷款者',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '投资者', 'verbose_name_plural': '投资者'},
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='passout_year',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='borrower',
            name='dwelling_condition',
            field=models.CharField(blank=True, choices=[('1', '商品房'), ('2', '经济适用房'), ('3', '自建私有房'), ('4', '租赁房')], default='无', max_length=50, null=True, verbose_name='住宅状况'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='dwelling_mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='家庭电话号码'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='dwelling_time',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='入住时间'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='family_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='家庭地址'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='identity_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='身份证号码'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_buy_car',
            field=models.BooleanField(default=False, verbose_name='是否购车'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='marriage_state',
            field=models.CharField(blank=True, choices=[('1', '未婚'), ('2', '已婚'), ('3', '丧偶'), ('4', '离婚')], default='无', max_length=50, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='pass_out_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='毕业日期'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('NONE', '无'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], default='NONE', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='EmploymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_state', models.CharField(blank=True, choices=[('employment', '已就业'), ('unemployment', '待业')], default='无', max_length=11, null=True, verbose_name='就业状态')),
                ('receive_wage', models.CharField(blank=True, choices=[('bank', '银行'), ('cash', '现金')], default='无', max_length=5, null=True, verbose_name='获得收入的方式')),
                ('company_type', models.CharField(blank=True, choices=[('1', '国家行政企业'), ('2', '公私合作企业'), ('3', '中外合资企业'), ('4', '社会组织机构'), ('5', '国际组织机构'), ('6', '外资企业'), ('7', '私营企业'), ('8', '集体企业'), ('9', '国防军事企业')], default='无', max_length=20, null=True, verbose_name='公司类型')),
                ('working_life', models.CharField(blank=True, max_length=4, null=True, verbose_name='工作年限')),
                ('company_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位名称')),
                ('working_department', models.CharField(blank=True, max_length=20, null=True, verbose_name='任职部门')),
                ('company_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司地址')),
                ('company_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司电话号码')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Borrower', verbose_name='工作单位')),
            ],
            options={
                'verbose_name': '工作单位',
                'verbose_name_plural': '工作单位',
            },
        ),
    ]
