# Generated by Django 2.2.6 on 2019-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191226_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='QQ号码'),
        ),
    ]
