# Generated by Django 2.2.6 on 2019-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_qq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentdetail',
            options={'verbose_name': '工作详情', 'verbose_name_plural': '工作详情'},
        ),
        migrations.AlterField(
            model_name='borrower',
            name='dwelling_condition',
            field=models.CharField(blank=True, choices=[('1', '商品房'), ('2', '经济适用房'), ('3', '自建私有房'), ('4', '租赁房'), ('5', '单位福利分房'), ('6', '学生宿舍')], default='1', max_length=50, null=True, verbose_name='住宅状况'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('NONE', '无'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], default='NONE', max_length=50, null=True, verbose_name='教育层次'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='marriage_state',
            field=models.CharField(blank=True, choices=[('1', '未婚'), ('2', '已婚'), ('3', '丧偶'), ('4', '离婚')], default='1', max_length=50, null=True, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='company_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='company_type',
            field=models.CharField(blank=True, choices=[('1', '国家行政企业'), ('2', '公私合作企业'), ('3', '中外合资企业'), ('4', '社会组织机构'), ('5', '国际组织机构'), ('6', '外资企业'), ('7', '私营企业'), ('8', '集体企业'), ('9', '国防军事企业')], default='无', max_length=30, null=True, verbose_name='公司类型'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='employment_state',
            field=models.CharField(blank=True, choices=[('employment', '已就业'), ('unemployment', '待业')], default='无', max_length=30, null=True, verbose_name='就业状态'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='receive_wage',
            field=models.CharField(blank=True, choices=[('bank', '银行'), ('cash', '现金')], default='无', max_length=20, null=True, verbose_name='获得收入的方式'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='working_department',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='任职部门'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='working_life',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='工作年限'),
        ),
    ]
