# Generated by Django 2.2.6 on 2019-12-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191228_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='pictures')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
