# Generated by Django 2.2.6 on 2020-01-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('slug', models.SlugField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='视频验证')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFamilyAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='user_authentication_data/%Y')),
                ('slug', models.SlugField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='家庭验证')),
            ],
        ),
    ]
