# Generated by Django 2.2.6 on 2020-01-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersfamilyauthentication_uservideoauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfamilyauthentication',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservideoauthentication',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
