# Generated by Django 2.2.6 on 2020-01-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200102_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersfamilyauthentication',
            old_name='image',
            new_name='file',
        ),
    ]
