# Generated by Django 2.2.6 on 2020-01-02 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200102_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfamilyauthentication',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='家庭验证'),
        ),
    ]
