# Generated by Django 2.2.6 on 2020-02-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200102_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', null=True, upload_to='image/%Y/%m'),
        ),
    ]
