# Generated by Django 2.2.6 on 2020-02-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_real_auth_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borroweruserprofile',
            options={'verbose_name': '借款者', 'verbose_name_plural': '借款者'},
        ),
    ]
