# Generated by Django 2.2.6 on 2020-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200216_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bitState',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='用户状态码'),
        ),
    ]
