# Generated by Django 2.2.6 on 2020-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_bitstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='real_auth_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='实名认证表'),
        ),
    ]
