# Generated by Django 2.2.6 on 2020-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200218_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bitState',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='用户状态码'),
        ),
    ]
