# Generated by Django 2.2.6 on 2020-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200222_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='风控累计分数'),
        ),
    ]
