# Generated by Django 2.2.6 on 2020-03-05 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userprofile_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_profile',
            new_name='userProfile',
        ),
    ]
