# Generated by Django 2.2.6 on 2020-03-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200328_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='fund_committed',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investment_limit',
        ),
    ]
